
server:
  port: 12345

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

spring:



  datasource:
    url: jdbc:postgresql://postgre:5432/userdatabase?ssl=false
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


eureka:
  instance:
    hostname: app-network
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka